### ISSUE TITLE
Upgrade to support dogwater 1.0.x.

### ISSUE THREAD

**Issue by devinivy** [devinivy/bedwetter#18]
See the dogwater milestone: https://github.com/devinivy/dogwater/milestones/1.0.0

**Comment by moklick** [comment]
Hey,

are you working on this? Can I help you with something?
I would really like to use bedwetter again, but now it's not possible because it doesn't satisfy its peerDependency requirements with dogwater..

**Comment by devinivy** [comment]
Hi @moklick–
I did start writing bedwetter v2.  It got halted for a while, as it became increasingly harder to get to 100% test coverage, which was one of my goals for v2.  I'm starting to wonder if that will be too daunting of a task, given my personal time constraints.  Perhaps I will only make the breaking changes and major bug fixes, release 2.0, then schedule the other features and test-writing for 2.1.

Do you have any thoughts on that, or suggestions?

**Comment by moklick** [comment]
sounds good. I think the most important part for now is that you can use it with current version of dogwater. 100% test coverage would be a good aim for 2.1.

**Comment by devinivy** [comment]
I agree.  Sorry for the hold-up.  If you are interested in picking-up this issue, feel free!  The update should not be terribly difficult, but if you haven't poked around this codebase before there may be a learning curve.

So you know the pending changes for 2.0, my working branch is called `coverage`.

**Comment by ccoenen** [comment]
Until then, a notice would be nice. I just sunk two hours of personal time into following a tutorial and wondering why Bedwetter wasn't picking up my Dogwater models. Google didn't really turn up anything. So if anyone else gets this error message, you may just try to combine the incompatible versions:

    Model user must exist to build route.

    at Object.exports.assert (\node_modules\hoek\lib\index.js:731:11)
    at \node_modules\bedwetter\lib\index.js:99:14
    at Object.exports.execute.internals.prerequisites.internals.handler.exports.configure (\node_modules\hapi\lib\handler.js:127:16)
    at new module.exports.internals.Route.options (\node_modules\hapi\lib\route.js:211:37)
    at internals.Connection._init.internals.Connection._start.internals.Connection._stop.internals.Connection._dispatch.internals.Connection.inject.internals.Connection._addRoute (\node_modules\hapi\lib\connection.js:370:19)

**Comment by neojp** [comment]
Came to this same issue when trying to use the `defaults` option on dogwater.

**Comment by millette** [comment]
I'm new to hapi. Currently using the https://github.com/edwinallenz/bedwetter fork with latest hapi and dogwater.

**Comment by casalot** [comment]
@millette, would you mind pasting a copy of your `package.json`?
